apiVersion: v1
kind: Service
metadata:
  name: myapp-app-secret-auth-service
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  selector:
    app: myapp
    version: app-secret-auth
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8888
  type: ClusterIP

