apiVersion: v1
kind: Service
metadata:
  name: myapp-postgres-iam-auth-service
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  selector:
    app: myapp
    version: postgres-iam-auth
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8888
  type: ClusterIP

